// <auto-generated />
using System;
using Events.Data.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Events.Data.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201124191908_RemoveIsAdmin")]
    partial class RemoveIsAdmin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Events.Data.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Badminton"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Social"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Video games"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Board games"
                        });
                });

            modelBuilder.Entity("Events.Data.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LockedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 8,
                            CategoryId = 1,
                            Date = new DateTimeOffset(new DateTime(2020, 11, 25, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Location = "Stratford Leisure Centre"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 8,
                            CategoryId = 1,
                            Date = new DateTimeOffset(new DateTime(2020, 12, 2, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Location = "Stratford Leisure Centre"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 8,
                            CategoryId = 1,
                            Date = new DateTimeOffset(new DateTime(2020, 12, 9, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Location = "Stratford Leisure Centre"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 8,
                            CategoryId = 1,
                            Date = new DateTimeOffset(new DateTime(2020, 12, 16, 18, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Location = "Stratford Leisure Centre"
                        });
                });

            modelBuilder.Entity("Events.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Events.Data.Model.UserCategoryTickets", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UserCategoryTickets");
                });

            modelBuilder.Entity("Events.Data.Model.UserEventSignUp", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEventSignUps");
                });

            modelBuilder.Entity("Events.Data.Model.Event", b =>
                {
                    b.HasOne("Events.Data.Model.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Events.Data.Model.UserCategoryTickets", b =>
                {
                    b.HasOne("Events.Data.Model.Category", "Category")
                        .WithMany("UserTickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Events.Data.Model.User", "User")
                        .WithMany("CategoryTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Events.Data.Model.UserEventSignUp", b =>
                {
                    b.HasOne("Events.Data.Model.Event", "Event")
                        .WithMany("UserSignUps")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Events.Data.Model.User", "User")
                        .WithMany("EventSignUps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Events.Data.Model.Category", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("UserTickets");
                });

            modelBuilder.Entity("Events.Data.Model.Event", b =>
                {
                    b.Navigation("UserSignUps");
                });

            modelBuilder.Entity("Events.Data.Model.User", b =>
                {
                    b.Navigation("CategoryTickets");

                    b.Navigation("EventSignUps");
                });
#pragma warning restore 612, 618
        }
    }
}
